### ISSUE TITLE
Images, but no data appear. 

### ISSUE THREAD

**Issue by dgarcia050186** [teese/eccpy#20]
Unclear why, but even with all dependencies installed the images of the curves appear, but none of the excel sheets showing the data appear. I should note the images have the EC50s.
May be a general excel issue as the template sheet only has the first data sheet read. The others are ignored. For instance, in the template, it reads dataset 0, but not 1 or 2. 
Any suggestions greatly appreciated.

**Comment by matzyy** [comment]
Hey,
"dependencies were based on Anaconda distribution 2020.07"
After struggling myself with it for 2 hours, I found out, that the note above is not just a recommendation. It is a hardcore guideline, and it isn't working with newer versions of python/pandas and even anaconda.
Regards, Matzy

**Comment by teese** [comment]
Sorry, I haven't been able to maintain eccpy, since I have neither a lab, nor funding. The students at the lab of Professor Langosch have presumably continued using eccpy with Anaconda 2020.07, because they haven't contacted me with any updates. I'll try to at least update the description with the current status.

**Comment by teese** [comment]
I've updated the readme and wiki to reflect the dependency on python 3.8 and the exact packages in the requirements.txt. My tests are green in this case, so I assume it solves the immediate problem. An upgrade of the code to a later version of python would be a better long-term solution.
