### ISSUE TITLE
Sample Replicates

### ISSUE THREAD

**Issue by jorgeholguin** [teese/eccpy#8]
When replicates of a single sample are added (using the exact same sample name) the values for the response of a given dose are not averaged and the error bars (SEM) are not displayed in the graph produced.

**Comment by teese** [comment]
Sorry for the late implementation. I haven't looked at eccpy for a long time and didn't realise there were open issues.
I assume this issue concerns the data collection for a single data-file (single day/run/experiment). I don't think there's any problem with the way mean values for multiple EC50 calculations are combined  over multiple experiments (by the run_gatherer scripts).
I've implemented the calculation of the mean values, but did not adjust the resulting figures.
Replicates within a single data-file are now summarised with a mean, n, and std.
This is saved in a new "by_sample" tab in the excel file for a single experiment (e.g. for the testdata: output/generated_data0/generated_data_0.xlsx).
As with the "run_gatherer" function, the sample names need to be identical for the replicates to be combined.
This change does not affect the functionality of the run_gatherer scripts, which collect all the data from all experiments as before.
lf you really want figures for a single experiment include the new means for replicates, please create a new issue. I personally think such functionality belongs in the run_gatherer scripts, in the form of an option to choose the "mean of daily means" rather than a "mean of individual replicates".
